# Dockerfile
FROM n8nio/n8n:latest

USER root

COPY n8n-workflows/Daily-Cache-Cleanup.json /home/node/workflows/Daily-Cache-Cleanup.json
# Copy and set entrypoint
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER node

ENTRYPOINT ["/entrypoint.sh"]